### ISSUE TITLE
Lesson maintainers

### ISSUE THREAD

**Issue by drjwbaker** [LibraryCarpentry/data-intro-archives-DEPRECATED#1]
This lesson needs at least 2 maintainers. If you want to do this (and/or want to know when this would entail, please say so below)

**Comment by ngeraci** [comment]
Hi, I'd possibly be interested-- what would it entail?

**Comment by drjwbaker** [comment]
@ngeraci Maintainers perform a number of important tasks:

- making sure their lesson is consistent with the other Library Carpentry lessons. For example, that the Readme or License pages are correct and consistent.
- addressing any issues that are raised against the lesson
- dealing with any pull requests that are made for the lesson.
- after a lesson is taught, making sure that suggestions for improvement from learners and instructors are integrated
- as this is a new lesson, helping it get through the incubator process https://github.com/data-lessons/librarycarpentry/issues/22
- and, ideally, keep up with general Library Carpentry chatter at https://gitter.im/weaverbel/LibraryCarpentry

All the work is voluntary and if you decide it is not for you, you can step back at any time (just let us know). Still interested?

**Comment by JennyBunn** [comment]
I'd be happy to take this on too, although I'm not sure I know how to deal with pull requests.

**Comment by weaverbel** [comment]
I can always deal with PRs if need be. It does require a bit of fiddly wrangling sometimes depending on the complexity.

**Comment by JennyBunn** [comment]
Thank you. I will try to work out how to do it, but am finding GitHub quite a steep learning curve. The principles make perfect sense, but the mechanics are proving a bit less transparent to me.

**Comment by weaverbel** [comment]
It has taken me twelve months of using it a LOT (and making many errors) to learn it so don't feel bad if it takes a while. I never thought I would manage it @JennyBunn but now I am OK with it and even like it.

**Comment by drjwbaker** [comment]
Well I'm down as a maintainer so I can handle PRs as well :) Thanks @JennyBunn. More maintainers still welcome @ngeraci, especially as you'd add to our timezone variety!

**Comment by ngeraci** [comment]
Sounds good-- happy to take this on.

**Comment by drjwbaker** [comment]
@ngeraci Splendid.

**Comment by drjwbaker** [comment]
README updated https://github.com/data-lessons/data-intro-archives/commit/0110cf32e6ca8e3f4609499facb1636f86dfafc3 Closing for now (though new lesson maintainers are welcome!)
